title: "polyglot cheat sheet"
theme: minima
email: thomas@thomaskuenneth.eu
header_pages:
  - methods_and_functions.md
  - variables_and_constants.md
  - control_flow.md
  - asynchronicity.md
  - arrows.md
