title: "polyglot cheat sheet"
theme: minima
email: thomas@thomaskuenneth.eu
header_pages:
  - Methods_and_functions.md
  - Variables_and_Constants.md
  - string_interpolation
  - conditions.md
  - for_loops.md
  - while_loops.md
  - asynchronicity.md
  - arrows.md
